plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from

disable_disk_cache: true
destination: _public

exclude:
  - rollup.config.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - wrangler.toml

markdown_ext: liquid,markdown,md

baseurl: '/'
permalink: date

pagination:
  enabled: true
  permalink: /:num/
  collection: all
  title: ':title - сторінка :num з :max'
  limit: 0
  per_page: 10
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2

title: Barbaricum
description: Навчальна науково-дослідна лабораторія археологічних досліджень

author:
  name: Barbaricum
  url: https://barbaricum.org/
  twitter: BarbaricumArch
  image:
    path: /images/banner.png
    height: 720
    width: 480

social:
  name: Barbaricum
  links:
    - https://twitter.com/BarbaricumArch
    - https://facebook.com/barbaricum
    - https://vk.com/barbaricum
    - https://www.instagram.com/_barbaricum_/

collections:


defaults:
  - scope:
      path: ''
    values:
      lang: uk
      layout: default